@Host = https://localhost:7023/api/appointments

### Get all

GET {{Host}}
ACCEPT: application/json

### Filter by name

GET {{Host}}?page=1&recordsPerPage=2&name=John+Smith
ACCEPT: application/json

### Search by Id

GET {{Host}}/9F8218AD-71B2-49E8-1DBE-08DEDE677B43
ACCEPT: application/json

### Insert

POST {{Host}}
Content-type: application/json

{
  "patientId": "5E02C2A4-6086-437F-D1A5-08DEE312AF4F",
  "dentistId": "3D335CDF-3340-4176-65F6-08DEE3532835",
  "dentistOfficeId": "019F1A17-158D-7CB5-A85D-4D84A9D5295E",
  "startDate": "2026-11-11T09:45:00",
  "endDate": "2026-11-11T10:15:00"
}

### Update by Appointment Status

POST {{Host}}/019F871B-22F4-7961-A908-45BB0458E346/complete
Content-type: application/json


### Delete by Id

DELETE {{Host}}/9c9324ad-aef1-4ca0-9472-08dee3f0c0f5