@Host = https://localhost:7023/api/appointments

### Get all

GET {{Host}}
ACCEPT: application/json

### Filter by name

GET {{Host}}?page=1&recordsPerPage=2&name=John+Smith
ACCEPT: application/json

### Search by Id

GET {{Host}}/9F8218AD-71B2-49E8-1DBE-08DEDE677B43
ACCEPT: application/json

### Insert

POST {{Host}}
Content-type: application/json

{
  "patientId": "5E02C2A4-6086-437F-D1A5-08DEE312AF4F",
  "dentistId": "3D335CDF-3340-4176-65F6-08DEE3532835",
  "dentistOfficeId": "019F1A17-158D-7CB5-A85D-4D84A9D5295E",
  "startDate": "2026-11-11T09:45:00",
  "endDate": "2026-11-11T10:15:00"
}

### Schedule Appointment by Id

POST {{Host}}/019F8A95-4030-775E-A8FB-A746A91A99AC/schedule
Content-type: application/json

### Complete Appointment by Id

POST {{Host}}/019F8A8D-6B52-7F1E-8256-C7B792F124E6/complete

### Cancel Appointment by Id

POST {{Host}}/019F8A93-4DE0-7C2D-A0C8-3F4EC337D44F/cancel