@Host = https://localhost:7023/api/appointments

### Get all

GET {{Host}}
ACCEPT: application/json

### Filter by name

GET {{Host}}?page=1&recordsPerPage=2&name=John+Smith
ACCEPT: application/json

### Search by Id

GET {{Host}}/af1fcd60-3bbc-4f52-ee00-08dee3556597
ACCEPT: application/json

### Insert

POST {{Host}}
Content-type: application/json

{
  "patientId": "9F8218AD-71B2-49E8-1DBE-08DEDE677B43",
  "dentistId": "AF1FCD60-3BBC-4F52-EE00-08DEE3556597",
  "dentistOfficeId": "019F1A44-442C-77C5-8F19-028EBC7BE2AD",
  "startDate": "2023-10-10T09:30:00",
  "endDate": "2023-10-10T10:45:00"
}

### Update by Id

PUT {{Host}}/3D335CDF-3340-4176-65F6-08DEE3532835
Content-type: application/json

{
  "name": "Dr. Sacha Porochock Junior",
  "email": "sachaporochockjunior@gmail.com"
}

### Delete by Id

DELETE {{Host}}/9c9324ad-aef1-4ca0-9472-08dee3f0c0f5