@Host = https://localhost:7023/api/dentists

### Get all

GET {{Host}}
ACCEPT: application/json

### Filter by name

GET {{Host}}?page=1&recordsPerPage=2&name=John+Smith
ACCEPT: application/json

### Search by Id

GET {{Host}}/5c72ea5b-2681-4cb2-ffca-08dede77b5bb
ACCEPT: application/json

### Insert

POST {{Host}}
Content-type: application/json

{
  "name": "Dr. Sacha Porochock",
  "email": "sachaporochock@gmail.com"
}

### Update by Id

PUT {{Host}}/7e137ce8-ab23-4fe0-e8de-08dedf8c34a9
Content-type: application/json

{
  "name": "David Lai",
  "email": "davidlai@gmail.com"
}

### Delete by Id

DELETE {{Host}}/7e137ce8-ab23-4fe0-e8de-08dedf8c34a9