@Host = https://localhost:7023/api/dentaloffices

GET {{Host}}
ACCEPT: application/json

###

GET {{Host}}/019f1a44-442c-77c5-8f19-028ebc7be2ad
ACCEPT: application/json

###

POST {{Host}}
Content-type: application/json

{
  "name": "Dental Office 2"
}

###

PUT {{Host}}/019f1a44-442c-77c5-8f19-028ebc7be2ad
Content-type: application/json

{
  "name": "Dental Office 2 - New"
}
