@Host = https://localhost:7023/api/patients

GET {{Host}}
ACCEPT: application/json

###

GET {{Host}}/9f8218ad-71b2-49e8-1dbe-08dede677b43
ACCEPT: application/json

###

POST {{Host}}
Content-type: application/json

{
  "name": "Marina Lai",
  "email": "marinalai@gmail.com"
}

###

PUT {{Host}}/9f8218ad-71b2-49e8-1dbe-08dede677b43
Content-type: application/json

{
  "name": "Dental Office 2 - New"
}

###

DELETE {{Host}}/019F183F-BD17-74A4-B564-B696C48DC608